cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY} # aws ??? ??? role? ???? access ? ?? ??? ?? .
      # local??? role? ??? ? ??. ?? ecs? ?? spring boot ??? role? ???? access ? ?? ??? ???? .
      # ecs task? role? ???? spring application? s3? ??? ???
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: myBucket
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
